#!/bin/bash
if [[ -z "AUTO_LOGIN_USER" ]]; then
    echo a user name must be given in order to login into destkop >&2
    exit 1    
fi

if [[ 0 != $UID ]]; then
    echo priveledged user is required >&2
    exit 1
fi

systemctl is-active lightdm >/dev/null && systemctl stop lightdm

systemctl start lightdm

python check_dde_dock.py
git clone https://github.com/wangyingtaodeepin/dogtail.git 
cd dogtail && python3 setup.py install
gsettings set org.gnome.desktop.interface toolkit-accessibility true

echo change user to $AUTO_LOGIN_USER
su - $AUTO_LOGIN_USER -c "who; ls -l"
su - $AUTO_LOGIN_USER -c "export DISPLAY=:0; git clone https://github.com/linuxdeepin/dsystem.git; cd dsystem && python3 lava_run.py"
